#ifndef _Task_h_
#define _Task_h_

/* 包含头文件 ----------------------------------------------------------------*/
#include "main.h"
#include "Button.h"
#include "Buzzer.h"
#include "Carrier.h"
#include "Control.h"
#include "RGB.h"
#include "Sensor.h"
#include "Servo.h"
#include "Track.h"
/* 类型定义 ------------------------------------------------------------------*/
typedef enum
{
  CARRIER_INIT = 0,  //机构调零
  START_AREA,  //出发区
  OUT_OF_START_AREA,  //驶离出发区
  FIRST_LINE,  //第一条线
  FIRST_CROSS,
  SECOND_LINE,  //第二条线
  SECOND_CROSS,
  THIRD_LINE,  //第三条线
  CATCH_FIRST_TARGET,  //抓取第一个目标
  AFTER_CATCH,
  BEFORE_THIRD_CROSS,
  THIRD_CROSS_PART_ONE,
  THIRD_CROSS_PART_TWO,
  AFTER_THIRD_CROSS,
  BEFORE_CATCH_PART_ONE,
  BEFORE_CATCH_PART_TWO,
  BEFORE_CATCH_PART_THREE,
  CATCH,
  BEFORE_UNLOAD,
  AFTER_CATCH_FIRST_TARGET_PART_ONE,
  AFTER_CATCH_FIRST_TARGET_PART_EX,
  AFTER_CATCH_FIRST_TARGET_PART_TWO,
  AFTER_CATCH_SECOND_TARGET,
  BEFORE_FOURTH_CROSS_PART_ONE,
  BEFORE_FOURTH_CROSS_PART_TWO,
  BEFORE_FOURTH_CROSS_PART_THREE,
  FOURTH_CROSS,
  AFTER_FOURTH_CROSS,
  FIFTH_CROSS_PART_ONE,
  FIFTH_CROSS_PART_TWO,
  FOURTH_LINE,
  FIFTH_LINE,
  BEFORE_SIXTH_LINE,
  SIXTH_LINE,
  BEFORE_SIXTH_CROSS,
  SIXTH_CROSS,
  AFTER_SIXTH_CROSS,
  BEFORE_SEVENTH_CROSS,
  SEVENTH_CROSS,
  AFTER_SEVENTH_CROSS,
  EIGHTH_CROSS,
  AFTER_EIGHTH_CROSS,
  BEFORE_NINETH_CROSS,
  NINETH_CROSS,
  AFTER_NINETH_CROSS,
  BEFORE_UNLOAD_SECOND_TARGET_PART_ONE,
  BEFORE_UNLOAD_SECOND_TARGET_PART_TWO,
  BEFORE_UNLOAD_SECOND_TARGET_PART_THREE,
  UNLOADING,
  AFTER_UNLOAD,
  BEFORE_TENTH_CROSS_PART_ONE,
  BEFORE_TENTH_CROSS_PART_TWO,
  BEFORE_TENTH_CROSS_PART_THREE,
  BEFORE_TENTH_CROSS_PART_FOUR,
  TENTH_CROSS,
  AFTER_TENTH_CROSS_PART_ONE,
  AFTER_TENTH_CROSS_PART_TWO,
  BEFORE_ELEVENTH_CROSS,
  ELEVENTH_CROSS,
  AFTER_ELEVENTH_CROSS,
  BEFORE_TWELFTH_CROSS,
  TWELFTH_CROSS,
  AFTER_TWELFTH_CROSS_PART_ONE,
  AFTER_TWELFTH_CROSS_PART_TWO,
  AFTER_CATCH_THIRD_TARGET,
  BEFORE_SEVENTH_LINE,
  THIRTEENTH_CROSS,
  AFTER_THIRTEENTH_CROSS,
  BEFORE_FOURTEENTH_CROSS,
  FOURTEENTH_CROSS,
  AFTER_FOURTEENTH_CROSS,
  BEFORE_FIFTEENTH_CROSS,
  AFTER_FIFTEENTH_CROSS,
  FIFTEENTH_CROSS,
  BEFORE_SIXTEENTH_CROSS,
  BEFORE_SIXTEENTH_CROSS_PART_ONE,
  BEFORE_SIXTEENTH_CROSS_PART_TWO,
  BEFORE_SIXTEENTH_CROSS_PART_THREE,
  BEFORE_SIXTEENTH_CROSS_PART_FOUR,
  SIXTEENTH_CROSS,
  AFTER_SIXTEENTH_CROSS,
  SIXTEENTH_CROSS_AGAIN,
  BEFORE_SEVENTEENTH_CROSS,
  SEVENTEENTH_CROSS,
  AFTER_SEVENTEENTH_CROSS,
  BEFORE_EIGHTEENTH_CROSS_PART_ONE,
  BEFORE_EIGHTEENTH_CROSS_PART_TWO,
  EIGHTEENTH_CROSS,
  AFTER_EIGHTEENTH_CROSS_PART_ONE,
  AFTER_EIGHTEENTH_CROSS_PART_TWO,
  AFTER_EIGHTEENTH_CROSS_PART_THREE,
  BEFORE_NINETEENTH_CROSS,
  AFTER_NINETEENTH_CROSS,
  NINETEENTH_CROSS,
  TWENTIETH_CROSS,
  AFTER_TWENTIETH_CROSS,
  BEFORE_TWENTY_FIRST_CROSS,
  TWENTY_FIRST_CROSS,
  AFTER_TWENTY_FIRST_CROSS,
  BEFORE_TWENTY_SECOND_CROSS,
  TWENTY_SECOND_CROSS,
  AFTER_TWENTY_SECOND_CROSS,
  BEFORE_TWENTY_THIRD_CROSS,
  TWENTY_THIRD_CROSS,
  AFTER_TWENTY_THIRD_CROSS,
  BEFORE_TWENTY_FOURTH_CROSS,
  TWENTY_FOURTH_CROSS,
  AFTER_TWENTY_FOURTH_CROSS,
  BEFORE_UNLOAD_FOURTH_TARGET_PART_ONE,
  BEFORE_UNLOAD_FOURTH_TARGET_PART_TWO,
  
  BEFORE_UNLOAD_THIRD_TARGET_PART_ONE,
  BEFORE_UNLOAD_THIRD_TARGET_PART_TWO,
  AFTER_CATCH_FOURTH_TARGET_PART_ONE,
  AFTER_CATCH_FOURTH_TARGET_PART_TWO,
  AFTER_CATCH_FOURTH_TARGET_PART_THREE,
  
  BEFORE_CATCH_FIFTH_TARGET_PART_ONE,
  BEFORE_CATCH_FIFTH_TARGET_PART_TWO,
  BEFORE_CATCH_FIFTH_TARGET_PART_THREE,
  BEFORE_CATCH_FIFTH_TARGET_PART_FOUR,
  BEFORE_CATCH_FIFTH_TARGET_PART_FIVE,
  BEFORE_CATCH_FIFTH_TARGET_PART_SIX,
  BEFORE_CATCH_FIFTH_TARGET_PART_SEVEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_EIGHT,
  BEFORE_CATCH_FIFTH_TARGET_PART_NINE,
  BEFORE_CATCH_FIFTH_TARGET_PART_TEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_ELEVEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_TWELVE,
  BEFORE_CATCH_FIFTH_TARGET_PART_THIRTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_FOURTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_FIFTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_SIXTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_SEVENTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_EIGHTEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_NINETEEN,
  BEFORE_CATCH_FIFTH_TARGET_PART_TWENTY,
  
  BEFORE_UNLOAD_FIFTH_TARGET_PART_ONE,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_TWO,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_THREE,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_FOUR,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_FIVE,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_SIX,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_SEVEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_EIGHT,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_NINE,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_TEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_ELEVEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_TWELVE,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_THIRTEEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_FOURTEEN,  
  BEFORE_UNLOAD_FIFTH_TARGET_PART_FIFTEEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_SIXTEEN,  
  BEFORE_UNLOAD_FIFTH_TARGET_PART_SEVENTEEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_EIGHTEEN,
  BEFORE_UNLOAD_FIFTH_TARGET_PART_NINETEEN,  
  BEFORE_UNLOAD_FIFTH_TARGET_PART_TWENTY,
  
  ENDING  //临时终点
}TASK_STATUS;// 任务状态

typedef enum
{
  FIRST_TARGET = 0,
  SECOND_TARGET,
  THIRD_TARGET,
  FOURTH_TARGET,
  FIFTH_TARGET,
}TARGET_NUMBER;
/* 宏定义 --------------------------------------------------------------------*/
/* 扩展变量 ------------------------------------------------------------------*/
extern uint8_t Target;
/* 函数声明 ------------------------------------------------------------------*/
void Task_TIM_Handle(void);
void Task_Delay_Start(unsigned int time);
unsigned char Task_Delay_Is_Delay(void);
void Task_TIM_Content(void);

#endif /* _Task_h_ */

/************************************************ 文件结束 ************************************************/
